spring.application.name=BeautySalonParser
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
google.places.base-url=
google.places.api-key=
server.port=8080